# Generated by Django 4.1.3 on 2022-12-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_carrito_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
