# Generated by Django 4.1.3 on 2022-11-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedore',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
