# Generated by Django 4.1.3 on 2022-11-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_proveedore_apellido_alter_proveedore_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
